// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScholarshipAutoFill.Api.Data;

#nullable disable

namespace ScholarshipAutoFill.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528075456_InitialProfileAndAnalysisSchema")]
    partial class InitialProfileAndAnalysisSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScholarshipAutoFill.Api.Domain.AnalysisLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ScholarshipAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScholarshipAnalysisId");

                    b.ToTable("AnalysisLogs");
                });

            modelBuilder.Entity("ScholarshipAutoFill.Api.Domain.ApplicantProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CefrLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cgpa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ExperienceSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("integer");

                    b.Property<string>("HighestDegree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IeltsListening")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IeltsOverall")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IeltsReading")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IeltsSpeaking")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IeltsWriting")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredRegions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResearchInterests")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScholarshipPreferences")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ApplicantProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Mohallah Dodal Shinkiari, Tehsil Baffa, District Mansehra, Pakistan",
                            CefrLevel = "B2",
                            Cgpa = "3.46 / 4.0",
                            CreatedAtUtc = new DateTime(2026, 5, 28, 7, 54, 52, 495, DateTimeKind.Utc).AddTicks(3651),
                            DateOfBirth = new DateOnly(1998, 12, 23),
                            Email = "Ubaidkhank1998@gmail.com",
                            ExperienceSummary = "2.5+ years as Software Engineer and Full Stack Developer",
                            FullName = "Muhammad Ubaid Khan",
                            Gender = "Male",
                            GraduationYear = 2021,
                            HighestDegree = "BS Software Engineering",
                            IeltsListening = "5.5",
                            IeltsOverall = "5.5",
                            IeltsReading = "5.0",
                            IeltsSpeaking = "6.5",
                            IeltsWriting = "5.5",
                            NationalId = "35200 2614337 1",
                            Nationality = "Pakistani",
                            PassportNumber = "NG4153372",
                            Phone = "+92 3125300827",
                            PlaceOfBirth = "Mansehra, Pakistan",
                            PreferredRegions = "Germany, Italy, Malaysia, Korea, China",
                            ResearchInterests = "Distributed systems, microservices architecture, full-stack development, AI-driven software engineering",
                            ScholarshipPreferences = "Fully funded or partially funded Master's scholarships. MOI-friendly universities preferred.",
                            Skills = ".NET Core, ASP.NET Core, Angular, Microservices, Docker, Kubernetes, Jenkins, RabbitMQ, Redis, WSO2, SQL Server, PostgreSQL, FinTech systems, Telecom systems, Distributed architecture, API integrations, Cloud deployment",
                            University = "Hazara University Mansehra",
                            UpdatedAtUtc = new DateTime(2026, 5, 28, 7, 54, 52, 495, DateTimeKind.Utc).AddTicks(3656)
                        });
                });

            modelBuilder.Entity("ScholarshipAutoFill.Api.Domain.RecommendedProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Deadline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DegreeLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnglishOrMoi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Risks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scholarship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ScholarshipAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.Property<string>("SourcesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScholarshipAnalysisId");

                    b.ToTable("RecommendedPrograms");
                });

            modelBuilder.Entity("ScholarshipAutoFill.Api.Domain.ResearchSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScholarshipAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScholarshipAnalysisId");

                    b.ToTable("ResearchSources");
                });

            modelBuilder.Entity("ScholarshipAutoFill.Api.Domain.ScholarshipAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScholarshipAnalyses");
                });

            modelBuilder.Entity("ScholarshipAutoFill.Api.Domain.ScholarshipOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Deadline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Eligibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ScholarshipAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScholarshipAnalysisId");

                    b.ToTable("ScholarshipOpportunities");
                });

            modelBuilder.Entity("ScholarshipAutoFill.Api.Domain.AnalysisLog", b =>
                {
                    b.HasOne("ScholarshipAutoFill.Api.Domain.ScholarshipAnalysis", null)
                        .WithMany("Logs")
                        .HasForeignKey("ScholarshipAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScholarshipAutoFill.Api.Domain.RecommendedProgram", b =>
                {
                    b.HasOne("ScholarshipAutoFill.Api.Domain.ScholarshipAnalysis", null)
                        .WithMany("RecommendedPrograms")
                        .HasForeignKey("ScholarshipAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScholarshipAutoFill.Api.Domain.ResearchSource", b =>
                {
                    b.HasOne("ScholarshipAutoFill.Api.Domain.ScholarshipAnalysis", null)
                        .WithMany("Sources")
                        .HasForeignKey("ScholarshipAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScholarshipAutoFill.Api.Domain.ScholarshipOpportunity", b =>
                {
                    b.HasOne("ScholarshipAutoFill.Api.Domain.ScholarshipAnalysis", null)
                        .WithMany("Scholarships")
                        .HasForeignKey("ScholarshipAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScholarshipAutoFill.Api.Domain.ScholarshipAnalysis", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("RecommendedPrograms");

                    b.Navigation("Scholarships");

                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
